export enum OperationTypeEnum {
    USER_CREATION = 'USER_CREATION',
    USER_INACTIVATION = 'USER_INACTIVATION',
    USER_ACTIVATION = 'USER_ACTIVATION',
    FEATURE_FLAG_CREATION = 'FEATURE_FLAG_CREATION',
    FEATURE_FLAG_ENABLE = 'FEATURE_FLAG_ENABLE',
    FEATURE_FLAG_DISABLE = 'FEATURE_FLAG_DISABLE'
}